apiVersion: v2
name: test-chart-yaml
version: 1.0.0

dependencies:
  - name: kube-state-metrics
    version: "4.14.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kubeStateMetrics.enabled
  - name: prometheus-node-exporter
    version: "3.3.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: nodeExporter.enabled
  - name: grafana
    version: "6.32.*"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled